[package]
name = "knockvpnrust"
version = "0.1.0"
edition = "2021"

[lib]
name = "knockvpnrust"
crate-type = ["cdylib"]

[dependencies]
jni = { version = "0.21.1", default-features = false }
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"  # Lightweight HTTP server